### ISSUE TITLE
Importing flows is not working

### ISSUE THREAD

**Issue by MMR100** [Jannik-Schilling/generate_swmm_inp#55]
When I generate inp file and use the attached Excel files for inflows, I don't see the inflows in my inp when opening with SWMM.

[5_1_gisswmm_inflows.xls](https://github.com/Jannik-Schilling/generate_swmm_inp/files/10837992/5_1_gisswmm_inflows.xls)

I am using SWMM 5.1.007

**Comment by Jannik-Schilling** [comment]
Hi, thanks for reporting your issue. The tool "2_GenerateSwmmInpFile" always checks if the node (junction, storage, divider, outlet) for the inflow exists in your layers, because otherwise SWMM will report an error ("Undefined Node"). 
So before you use the tool, make shure, that the nodes (3788, 3790, 3791) are in the chosen layers.

Does this solve your issue?

**Comment by MMR100** [comment]
I found details on the issue.
If all my junction are numbers (3788, 3790,etc.) , the inp file doesn't have inflow.
If I add one junction with text (let say "junction1"), then the inp file has all the inflows working. I tried with this added junction at the beginning or the end of all the junctions, it work in both cases.

**Comment by Jannik-Schilling** [comment]
ok, I get it... should be fixed with https://github.com/Jannik-Schilling/generate_swmm_inp/commit/bf5da28e188a3bc61a67fe5cac90f0d13b8c7c7b ; the next version will join the inflows properly without your workaround; until the release you know what to do :-)

**Comment by Jannik-Schilling** [comment]
[615210c](https://github.com/Jannik-Schilling/generate_swmm_inp/commit/615210cd7bb09cc9432f0be702b1af6c75613b33)
