### ISSUE TITLE
Error message - NameError: name 'self' is not defined

### ISSUE THREAD

**Issue by amgeda1508** [Jannik-Schilling/generate_swmm_inp#77]
Hi, what to do with this error message for running the tool?

![Inked1](https://github.com/Jannik-Schilling/generate_swmm_inp/assets/145666884/5aa86d22-f0a1-439d-b7d1-fbbd3d5ef944)
![2](https://github.com/Jannik-Schilling/generate_swmm_inp/assets/145666884/0a0cd84e-9c5c-4b6f-8b7d-10df884d2b7f)

**Comment by Jannik-Schilling** [comment]
Hey @amgeda1508,
the problem is a missing python package which you need to write a table file (xlsx, xls, or odf). You can install either the package "openpyxl" or "odf". Instructions can be found here: https://github.com/Jannik-Schilling/generate_swmm_inp#0-install

Sorry for the bad error message, I'll improve this soon.

**Comment by amgeda1508** [comment]
It works: python -m pip install openpyxl 
Thank you!

**Comment by Jannik-Schilling** [comment]
08c4d29
